port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
  - name: https://youtube.com/c/AdyBatei
    type: ss
    server: id-ss.sshmax.xyz
    port: 1443
    cipher: chacha20-ietf-poly1305
    password: YjljYmEz
    udp: true
  - name: shadowsocksr
    type: ssr
    server: sg1socks.serverssh.net
    port: 8383 
    cipher: AES-256-CFB
    password: u2VFHYXPyT
    obfs: tls1.2_ticket_auth
    protocol: auth_chain_a
    obfs-param: bimbel.ruangguru.com
    protocol-param: 
    udp: true
proxy-groups:
  - name: Manual Server
    type: select
    proxies:
      - "Best Ping ✓"
      - "https://youtube.com/c/AdyBatei"
      - "shadowsocksr"
  - name: Best Ping ✓
    type: url-test
    proxies:
      - "https://youtube.com/c/AdyBatei"
      - "shadowsocksr"
    url: https://www.google.com/
    interval: 300
  - name: "LOAD BALANCE"
    type: load-balance
    proxies:
      - "https://youtube.com/c/AdyBatei" 
      - "shadowsocksr"
    url: 'https://www.google.com/'
    interval: 300
  - name: "Fallback"
    type: fallback
    proxies:
      - "https://youtube.com/c/AdyBatei"
      - "shadowsocksr"
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
rules:
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - IP-CIDR6,fd00::/8,DIRECT,no-resolve
  - DOMAIN-SUFFIX,ad.com,REJECT
  - DOMAIN,analytics.google.com,REJECT
  - DOMAIN,analyticsinsights-pa.googleapis.com,REJECT
  - DOMAIN,analyticsreporting.googleapis.com,REJECT
  - DOMAIN-SUFFIX,doubleclick.net,REJECT
  - DOMAIN-SUFFIX,googleadservices.com,REJECT
  - DOMAIN-SUFFIX,googleadsserving.cn,REJECT
  - DOMAIN-SUFFIX,googlesyndication.com,REJECT
  - DOMAIN-SUFFIX,googletagmanager.com,REJECT
  - DOMAIN-SUFFIX,googletagservices.com,REJECT
  - DOMAIN-SUFFIX,google-analytics.com,REJECT
  - DOMAIN-KEYWORD,adservice,REJECT
  - DOMAIN-KEYWORD,analytics,REJECT
  - DOMAIN-KEYWORD,analysis,REJECT
  - SRC-IP-CIDR,192.168.1.201/32,DIRECT
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - GEOIP,IR,DIRECT
  - MATCH,, Manual Server , LOAD BALANCE , Fallback , dns-failed

































